---
title: "301 Project"
author: "Rodriguez"
date: "2023-04-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
mydat <- Wastedata2
```

```{r}
#Research Question 1
RQ1 <- NULL
RQ1 <- mydat %>% dplyr::select(Year, County, Recycling) %>% mutate(pctChange = 0) %>% arrange(County) %>% filter(Year == 1991 | Year == 1997|Year==2002|Year == 2007|Year== 2012| Year==2017) # Create a dataframe for this question

#Calculate percent change
for (i in 0:85){ # Num Counties
  for (j in 2:6) { #Num Years, skip over first year as it's NA
    RQ1$pctChange[6*i+j] <- (RQ1$Recycling[6*i + j]-RQ1$Recycling[6*i + j-1])/RQ1$Recycling[6*i + j-1] * 100
  }
}
#Remove NAs
RQ1 <- RQ1 %>% filter(Year == 1997|Year==2002|Year == 2007|Year== 2012| Year==2017)
#Change to factor
RQ1$Year <- as.factor(RQ1$Year)
#Rename factor for graph readability
levels(RQ1$Year) <- c("1991 to 1997", "1997 to 2002", "2002 to 2007","2007 to 2012","2012 to 2017") 
RQ1 %>% group_by(Year) %>% summarise(avgPct = mean(pctChange), avgRecycling = mean(Recycling)) #Exploratory Data Analysis

```

```{r}
#Testing Sphericity
library(rstatix)
model <- anova_test(data = RQ1, dv = pctChange, wid = County, within = Year)
model
#Assumption violated, use GGe DF adjustment
```

```{r}
library(nlme) # for lme
#Create One way repeated measure ANOVA model for posthoc
RQ1model <- lme(pctChange ~ Year, random = ~1 | County, data = RQ1) 
anova(RQ1model)

library(multcomp) #for glht
RQ1posthoc <- glht(RQ1model, linfct = mcp(Year = "Tukey"))
summary(RQ1posthoc)
```



```{r}
# Create Bar Chart
RQ1 %>% group_by(Year) %>% summarise(avgPct = mean(pctChange), sePct = sd(pctChange)/ sqrt(length(pctChange)), tstar = qt(1-0.05/2, length(pctChange)-1)) %>%#Calculate Error bars
  ggplot(aes(x = Year, y = avgPct)) + geom_point(data = RQ1, aes(x = Year, y = pctChange), position = position_jitter(.3))  + #plot County points, and jitter
  geom_point(color = "red", size = 2) + #Plot mean in red
  geom_errorbar(aes(ymin = avgPct - tstar * sePct, ymax = avgPct + tstar * sePct), color = "red") + #Plot Error Bars in red
  labs(title = "Dot Plot of Percent Change by County with Averages Superimposed in Red", y = "Percent Change", x = "Year Range")

```

#Research Question 2
```{r}
RQ2 <- mydat
sortRQ2 <- RQ2 %>% group_by(County) %>% summarise(avgOrg = mean(Organics), avgOnSite = mean(Onsite), avgWTE = mean(WTE), avgLandf = mean(Landfilled)) %>% arrange(avgOnSite)
sortRQ2
#Used the above to select the following vectors
lowTier <- sortRQ2$County[c(1,4:17)]
midTier <- sortRQ2$County[36:50]
topTier <- sortRQ2$County[72:86]

RQ2 <- RQ2 %>% filter(Year == 2017) %>% filter(County %in% lowTier | County %in% midTier | County %in% topTier) %>% # Remove all counties not in the list,
  mutate(OnsiteTier = ifelse(County %in% lowTier, "Low Tier",  ifelse(County %in% midTier, "Mid Tier" , ifelse(County %in% topTier, "Top Tier", 0))))  %>% #Create indicators
  dplyr::select(Year, County, Landfilled, OnsiteTier) %>% arrange(Year, OnsiteTier) #Remove unneeded data
RQ2
```

```{r}
#Assess variance assumption with a Box plot and Barlett's test
boxplot(Landfilled ~ OnsiteTier, data = RQ2, main = "Boxplot of Landfilled Waste by Onsite Recycling Tier")
bartlett.test(Landfilled ~ OnsiteTier, data = RQ2)
```

```{r}
#Run One Way ANOVA test
RQ2 %>% group_by(OnsiteTier) %>% summarise(avgLf = mean(Landfilled))
RQ2Model <- aov(Landfilled ~ OnsiteTier, data = RQ2)
summary(RQ2Model)
```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
